Using bash on Windows CI.

diff --git a/.github/workflows/windows.yml b/.github/workflows/windows.yml
--- a/.github/workflows/windows.yml
+++ b/.github/workflows/windows.yml
@@ -24,11 +24,13 @@ jobs:
     steps:
       - uses: actions/checkout@v2
       - name: Setup python
+        shell: bash
         run: |
             python -m pip install twine pytest numpy setuptools wheel 
 
       # Runs a set of commands using the runners shell
       - name: Build using MSVS
+        shell: bash
         run: |
           mkdir build
           cd build
@@ -37,9 +39,10 @@ jobs:
           ctest -C Release
 
       - name: Upload to PyPI
+        shell: bash
         env:
            SMOLDYN_PYPI_TOKEN: ${{ secrets.SMOLDYN_PYPI_TOKEN }}
         run: |
             cd build
             ls 
-            python -m twine upload -u __token__ -p "$env:SMOLDYN_PYPI_TOKEN" *.whl --skip-existing
+            python -m twine upload -u __token__ -p "$env:SMOLDYN_PYPI_TOKEN" *.whl --skip-existing || echo "Failed to upload"
